# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neuron < Formula
  desc "🧠 Your second brain, from the terminal. Obsidian-compatible + AI + MCP."
  homepage "https://github.com/steevin/neuron-cli"
  version "1.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.0.11/neuron_1.0.11_darwin_amd64.tar.gz"
      sha256 "9551f75c0d91fa8bb6e1a553c25a1f0c0ec344a66b7812c8762c165d1387f6a2"

      define_method(:install) do
        bin.install "neuron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.0.11/neuron_1.0.11_darwin_arm64.tar.gz"
      sha256 "0fd09f6e17af335c6775bf635146750ed409cc388d334cf3a4b2a3c403e8cf1a"

      define_method(:install) do
        bin.install "neuron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.0.11/neuron_1.0.11_linux_amd64.tar.gz"
      sha256 "431a18165fd46f08a8403d7190ea1c9dd1cf2d2d59e36e7e549772a979a4ec57"
      define_method(:install) do
        bin.install "neuron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.0.11/neuron_1.0.11_linux_arm64.tar.gz"
      sha256 "5324017dd01b09a86e8307848b0426f54442c3c869bb5a1d3792767fa151f987"
      define_method(:install) do
        bin.install "neuron"
      end
    end
  end

  test do
    system "#{bin}/neuron version"
  end
end
