# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neuron < Formula
  desc "🧠 Your second brain, from the terminal. Obsidian-compatible + AI + MCP."
  homepage "https://github.com/steevin/neuron-cli"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.2.2/neuron_1.2.2_darwin_amd64.tar.gz"
      sha256 "ff3355bfc3b002e9db90a70c508a913717e57fc01109c08b5af085621b54f857"

      define_method(:install) do
        bin.install "neuron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.2.2/neuron_1.2.2_darwin_arm64.tar.gz"
      sha256 "7aec04e58d638cabe7b920b27e665dc83749094dd15a52c90049cbd5d85ca2a2"

      define_method(:install) do
        bin.install "neuron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.2.2/neuron_1.2.2_linux_amd64.tar.gz"
      sha256 "7c584908a73cd77ce52749fa66e481d1862f6e14b80f479d9ed22d14bac04e5d"
      define_method(:install) do
        bin.install "neuron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steevin/neuron-cli/releases/download/v1.2.2/neuron_1.2.2_linux_arm64.tar.gz"
      sha256 "c7a78eb041cf7da88791dd32e2738020cb44c706569c076bacec1649c320c4ad"
      define_method(:install) do
        bin.install "neuron"
      end
    end
  end

  test do
    system "#{bin}/neuron version"
  end
end
